---
title: "Assignment 2"
author: "Insert My Name"
date: "2024-09-25"
output: html_document # you can change to other output format if you want
---

```{r}
library(tidyverse)
library(Stat2Data)
data("Hawks")

```

# 1. Data Wrangling
```{r}
head(Hawks,5)
```
## 1.1 (Q1)   
```{r}

hSF <-
  Hawks%>%filter(Species=="RT" & Weight>=1000)%>%select(Wing,Weight,Tail)
head(hSF,5)

hSF%>%nrow()
```
## 1.1 (Q2)   

## 1.2 (Q1)
```{r}
a <- hSF%>%arrange(Wing)
head(a,5)
``` 
## 1.3 Q1
```{r}
species_code<-c("CH","RT","SS")
species_name_full<-c("Cooper's","Red-tailed","Sharp-shinned")
hawkSpeciesNameCodes<-data.frame(species_code,species_name_full)
hawkSpeciesNameCodes
```
## Q2
```{r}
hawksFullName <- Hawks %>%
  left_join(hawkSpeciesNameCodes %>%
    rename(Species = species_code)) %>%
  select(-Species) %>%
  rename(Species = species_name_full)
```
## Q3
```{r}
hawksFullName %>%
  select(Species,Wing,Weight) %>%
  head(7)
```


## 1.4
```{r}
hawksWithBMI <- Hawks %>%
mutate(bird_BMI=1000*Weight/Wing^2)%>%
select(Species, bird_BMI)%>%
arrange(desc(bird_BMI))
```
## 1.5
```{r}
hawksFullName %>%
group_by(Species)%>%
summarize(num_rows=n(),
mn_wing=mean(Wing, na.rm=TRUE),
md_wing=median(Wing,na.rm=TRUE),
t_mn_wing=mean(Wing,na.rm=TRUE, trim=0.1),
b_wt_ratio=max(Wing/Tail,na.rm=TRUE))
#当 na.rm = TRUE 时，函数会忽略数据中的缺失值进行计算；如果 na.rm = FALSE（默认值），则如果存在 NA，结果会返回 NA
```
# 2. Random experiments, events and sample spaces, and the set theory

....

# 3. Probability theory

## 3 (Q1)

## 3 (Q2)

.....



